const app = require("./app");
//to use dot env variables import it
const dotenv = require("dotenv");
const cloudinary=require("cloudinary");
// import db function
const connectDB = require("./config/database");
//handling uncaught exceptions like printing somethig that is nto defined nothing else can catch this error sowe write this
process.on("uncaughtException",(err)=>{
   //err.messgae is generated by console
   console.log(`Error:${err.message}`);
   console.log(`Shutting down the server due to uncaught exception`);
   process.exit(1);

});

// specify location of dotenv file
dotenv.config({
  path: "backend/config/config.env",
});
//connecting to db by calling db function
connectDB();
cloudinary.config({
  // details will be clodinary account
  cloud_name: process.env.CLOUDINARY_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
})

//listening to server
//process.env.PORT variable is imported from config.env file
const server = app.listen(process.env.PORT, () => {
  console.log(`Server is running at http://localhost:${process.env.PORT}`);
});
//unhandled promise rejection>if db_uri is wrong well forcefully shut the server
process.on("unhandledRejection", (err) => {
  console.log(`Error: ${err.message}`);
  console.log(`Shutting down the server due to unhandled promise rejecetion`);

  server.close(() => {
    process.exit(1);
  }); //when server is closed come out of the process
  //since we have handled error here we canremove catch from databse.js as it will log errors 
});
